tasks:
  task-a:
    rss: https://rarbg.to/rssdd.php?categories=14;15;16;17;21;22;42;44;45;46;47;48
    quality:
      - 1080p
    regexp:
      accept:
        - webrip
    transmission:
      path: /completed
