tasks:
  task-a:
    rss: https://sukebei.nyaa.si/?page=rss&q=HD&c=0_0&f=0&u=offkab
    accept_all: yes
    content_filter:
     require_all:
      - '*.mkv'
      - '*.mp4'
      - '*.srt'
    transmission: yes
  task-b:
    rss: https://sukebei.nyaa.si/?page=rss&q=Uncensored&c=0_0&f=0&u=NewDragon
    accept_all: yes
    content_filter:
     require_all:
      - '*.mkv'
      - '*.mp4'
    transmission: yes
